/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BUS.*;
import DAO.*;
import com.formdev.flatlaf.intellijthemes.FlatArcOrangeIJTheme;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

import com.formdev.flatlaf.intellijthemes.FlatCyanLightIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatDarkPurpleIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoDarkFuchsiaIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoDeepOceanIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubDarkIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDarkerIJTheme;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMoonlightIJTheme;
import java.sql.Timestamp;
import java.util.List;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.UIManager;
import javax.swing.UIManager;

/**
 *
 * @author M S I
 */
public class QuanLyThanhVien extends javax.swing.JFrame {

    ThanhVienBUS thanhVienBUS = new ThanhVienBUS();
    ThongTinSDBUS thongTinSdBUS = new ThongTinSDBUS();
    ThietBiBUS thietBiBUS = new ThietBiBUS();
    List<ThongTinSD> listDatathongtin;
    /**
     * Creates new form QuanLyThanhVien
     */
    public QuanLyThanhVien() {
        try {
            UIManager.setLookAndFeel(new FlatDarkPurpleIJTheme());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        initComponents();

        loadDanhSachThanhVien();
        loadThongTinSDTable();
        loadDanhSachMuonTra();
    }

    public void loadDanhSachThanhVien() {
        DefaultTableModel model = (DefaultTableModel) danhSachThanhVien.getModel();
        model.setRowCount(0); // xóa table 

        for (ThanhVien thanhVien : thanhVienBUS.layDanhSachThanhVien()) {

            Object[] dataRow = new Object[5];
            dataRow[0] = thanhVien.getMaTV();
            dataRow[1] = thanhVien.getHoTen();
            dataRow[2] = thanhVien.getKhoa();
            dataRow[3] = thanhVien.getNganh();
            dataRow[4] = thanhVien.getSDT();
            model.addRow(dataRow);
        }
        danhSachThanhVien.setModel(model);
    }
    
    public void loadDanhSachMuonTra() {
        DefaultTableModel model = (DefaultTableModel) tableThongTinSuDung.getModel();
        model.setRowCount(0); // xóa table 

        for (ThongTinSD thongTinMuonTra : thongTinSdBUS.layDanhSachMuonTra()) {
            if(thongTinMuonTra.getMaTB() == null) {
                continue;
            }
            Object[] dataRow = new Object[5];
            dataRow[0] = thongTinMuonTra.getMaTT();
            dataRow[1] = thongTinMuonTra.getMaTV().getMaTV();
            dataRow[2] = thongTinMuonTra.getMaTB().getMaTB();
            dataRow[3] = thongTinMuonTra.getTGMuon();
            dataRow[4] = thongTinMuonTra.getTGTra();
            model.addRow(dataRow);
        }
        tableThongTinSuDung.setModel(model);
    }
     
    public void loadThongTinSDTable() {
        listDatathongtin = thongTinSdBUS.loadthongtinsd();
        DefaultTableModel model = (DefaultTableModel) tblTTSD.getModel();
        model.setRowCount(0);
        ThanhVien tv;
        for (ThongTinSD rowDatathongtin : listDatathongtin) {
            tv = thanhVienBUS.CheckThanhVienVaoKhuHocTap(rowDatathongtin.getMaTV().getMaTV());
            if (tv != null) {
                model.addRow(new Object[]{rowDatathongtin.getMaTT(), tv.getMaTV(), tv.getHoTen(), tv.getKhoa(), tv.getNganh(), tv.getSDT(), rowDatathongtin.getTGVao()});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnXoaThanhVien = new javax.swing.JButton();
        btnNhapFileTv = new javax.swing.JButton();
        btnSuaTv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaThanhVien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNganh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        btnThemThanhVien = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        danhSachThanhVien = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        txtNamThanhLap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnXoaNhieuThanhVien = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTTSD = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        TexMaTV = new javax.swing.JTextField();
        btnConfirm = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelMuonTra = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtMaTV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnMuonThietBi = new javax.swing.JButton();
        txtMaThietBiMuon = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btnTraThietBi = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtMaThietBiTra = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableThongTinSuDung = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thao tác"));

        btnXoaThanhVien.setText("Xóa");
        btnXoaThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaThanhVienActionPerformed(evt);
            }
        });

        btnNhapFileTv.setText("Nhập");
        btnNhapFileTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapFileTvActionPerformed(evt);
            }
        });

        btnSuaTv.setText("Sửa");
        btnSuaTv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSuaTv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhapFileTv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNhapFileTv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaTv, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin thành viên"));

        jLabel1.setText("Mã");

        jLabel2.setText("Họ Tên");

        jLabel3.setText("Khoa");

        jLabel4.setText("Ngành");

        jLabel5.setText("Số điện thoại");

        btnThemThanhVien.setText("Thêm");
        btnThemThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemThanhVienActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaThanhVien)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtNganh, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnThemThanhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThemThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách thành viên"));

        danhSachThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã", "Họ Tên", "Khoa", "Ngành", "Số Điện Thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        danhSachThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                danhSachThanhVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(danhSachThanhVien);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Xóa nhiều thành viên"));

        jLabel6.setText("Năm thành lập");

        btnXoaNhieuThanhVien.setText("Xóa");
        btnXoaNhieuThanhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhieuThanhVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamThanhLap, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaNhieuThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(521, 521, 521))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamThanhLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(btnXoaNhieuThanhVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thành viên", jPanel2);

        jPanel7.setBackground(java.awt.Color.white);

        tblTTSD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MaTT", "MaTV", "Họ Tên", "Khoa", "Ngành", "SÐT", "Thời Gian Vào"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTTSD.setToolTipText("");
        jScrollPane1.setViewportView(tblTTSD);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel7.setText("Mã Thành Viên:");

        btnConfirm.setText("Xác Nhận");
        btnConfirm.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 19)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Khu Vực Học Tập");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TexMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addGap(293, 293, 293))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TexMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConfirm)))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Khu học tập", jPanel1);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Mượn thiết bị"));

        jLabel9.setText("Mã thành viên");

        jLabel10.setText("Thiết bị");

        btnMuonThietBi.setText("Mượn thiết bị");
        btnMuonThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuonThietBiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMuonThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaThietBiMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaTV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaThietBiMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(btnMuonThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Trả thiết bị"));

        btnTraThietBi.setText("Trả thiết bị");
        btnTraThietBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraThietBiActionPerformed(evt);
            }
        });

        jLabel11.setText("Thiết bị");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaThietBiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(btnTraThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMaThietBiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sử dụng"));

        tableThongTinSuDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã thông tin", "Mã thành viên", "Mã thiết bị", "Thời gian mượn", "Thời gian trả"
            }
        ));
        tableThongTinSuDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThongTinSuDungMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableThongTinSuDung);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMuonTraLayout = new javax.swing.GroupLayout(jPanelMuonTra);
        jPanelMuonTra.setLayout(jPanelMuonTraLayout);
        jPanelMuonTraLayout.setHorizontalGroup(
            jPanelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMuonTraLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMuonTraLayout.setVerticalGroup(
            jPanelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMuonTraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMuonTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mượn, trả thiết bị", jPanelMuonTra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // đẩy dữ liệu 1 thành viên lên các textbox
    public void setThanhVienModel(ThanhVien thanhVien) {
        txtMaThanhVien.setText(thanhVien.getMaTV() + "");
        txtHoTen.setText(thanhVien.getHoTen() + "");
        txtKhoa.setText(thanhVien.getKhoa() + "");
        txtNganh.setText(thanhVien.getNganh() + "");
        txtSoDienThoai.setText(thanhVien.getSDT() + "");
    }

    // xử lý khi ấn chọn 1 dòng trên bảng thành viên
    private void danhSachThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_danhSachThanhVienMouseClicked
        // lấy ra số dòng được chọn
        int row = danhSachThanhVien.rowAtPoint(evt.getPoint());
        // lấy ra id khóa học từ dòng được chọn
        int maTV = Integer.parseInt(danhSachThanhVien.getValueAt(row, 0).toString());
        ThanhVien thanhVien = thanhVienBUS.layThanhVienQuaID(maTV);
        setThanhVienModel(thanhVien);
        txtMaThanhVien.setEnabled(false);


    }//GEN-LAST:event_danhSachThanhVienMouseClicked

    // làm mới dữ liệu form thành viên
    public void resetFormThanhVien() {
        txtMaThanhVien.setEnabled(true);
        txtMaThanhVien.setText("");
        txtHoTen.setText("");
        txtKhoa.setText("");
        txtNganh.setText("");
        txtSoDienThoai.setText("");
        loadDanhSachThanhVien();
    }

    // xử lý sự kiện khi ấn nút xóa thành viên
    private void btnXoaThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaThanhVienActionPerformed
        // TODO add your handling code here:
        if (!txtMaThanhVien.getText().isEmpty()) {
            int maTV = Integer.parseInt(txtMaThanhVien.getText());
            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa thành viên?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                if (thanhVienBUS.xoaThanhVienTheoID(maTV)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành viên thành công");
                    loadDanhSachThanhVien();
                    resetFormThanhVien();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành viên thất bại");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thành viên cần xóa");
        }
    }//GEN-LAST:event_btnXoaThanhVienActionPerformed

    // xử lý sự kiện ấn nút làm mới các trường dữ liệu
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        resetFormThanhVien();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaNhieuThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhieuThanhVienActionPerformed
        // TODO add your handling code here:
        if (txtNamThanhLap.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập năm thành lập");
        } else {
            if (thanhVienBUS.xoaThanhVienTheoKhoa(Integer.parseInt(txtNamThanhLap.getText()))) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDanhSachThanhVien();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaNhieuThanhVienActionPerformed

    private void btnThemThanhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemThanhVienActionPerformed
         String maTV,HoTen,Khoa,Nganh,SDT;
        boolean ketqua; 
        if(kiemTraRong()) {
             maTV = txtMaThanhVien.getText().trim();
             HoTen = txtHoTen.getText().trim();
             Khoa = txtKhoa.getText().trim();
             Nganh = txtNganh.getText().trim();
             SDT = txtSoDienThoai.getText().trim();
             
            if(thanhVienBUS.kiemTraTrungId(maTV)){
                    ketqua = thanhVienBUS.insertThanhVien(Integer.parseInt(maTV), HoTen, Khoa, Nganh, SDT);
                   if(ketqua){
                       loadDanhSachThanhVien();
                       JOptionPane.showMessageDialog(this, "Thêm thành công!");
                   }else {
                       JOptionPane.showMessageDialog(this, "Thêm thất bại!");
                   }
            }else {
                JOptionPane.showMessageDialog(this, "Mã bị trùng!");
            }
             
        }else {
            JOptionPane.showMessageDialog(this, "Ô dữ liệu bị rỗng hoặc không hợp lệ!");      
        }
    }//GEN-LAST:event_btnThemThanhVienActionPerformed

    private void btnSuaTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTvActionPerformed

        String maTV,HoTen,Khoa,Nganh,SDT;
        boolean ketqua; 
        if(kiemTraRong()) {
             maTV = txtMaThanhVien.getText().trim();
             HoTen = txtHoTen.getText().trim();
             Khoa = txtKhoa.getText().trim();
             Nganh = txtNganh.getText().trim();
             SDT = txtSoDienThoai.getText().trim();
             
            if(!thanhVienBUS.kiemTraTrungId(maTV)){
                    ketqua = thanhVienBUS.updateThanhVien(Integer.parseInt(maTV), HoTen, Khoa, Nganh, SDT);
                   if(ketqua){
                       loadDanhSachThanhVien();
                       JOptionPane.showMessageDialog(this, "Sửa thành công!");
                   }else {
                       JOptionPane.showMessageDialog(this, "Sửa thất bại!");
                   }
            }else {
                JOptionPane.showMessageDialog(this, "Mã thành viên không tồn tại!");
            }
             
        }else {
            JOptionPane.showMessageDialog(this, "Ô dữ liệu bị rỗng hoặc không hợp lệ!");      
        }
    }//GEN-LAST:event_btnSuaTvActionPerformed

    private void btnNhapFileTvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapFileTvActionPerformed
        // TODO add your handling code here:
    boolean ketqua = thanhVienBUS.themDS();
    if(ketqua){
        loadDanhSachThanhVien();
         JOptionPane.showMessageDialog(null, "Thêm thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }else
        JOptionPane.showMessageDialog(null, "Thêm thất bại", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnNhapFileTvActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        try {
            String maTVText = TexMaTV.getText().trim();
            if (maTVText.equals("")) {
                JOptionPane.showMessageDialog(this, "Mã Thành Viên không được để trống", "Lỗi", JOptionPane.ERROR_MESSAGE);
                TexMaTV.setText("");
            } else {
                if (!maTVText.matches("\\d+")) {
                    JOptionPane.showMessageDialog(this, "Mã Thành Viên chỉ chứa số", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    TexMaTV.setText("");
                    return;
                }
                long maTV = Long.parseLong(maTVText);
                ThongTinSD ttsd = new ThongTinSD();
                List<ThongTinSD> listMaTT=thongTinSdBUS.loadthongtinsdMaTT();
                ttsd.setMaTT(listMaTT.size() + 1);
                ThanhVien tvInput = new ThanhVien();
                tvInput.setMaTV((int) maTV);
                LocalDateTime ldt = LocalDateTime.now();
                String strdate = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(ldt);
                Timestamp timestamp = Timestamp.valueOf(strdate);
                ttsd.setTGVao(timestamp);
                ThanhVien tvResult = thanhVienBUS.CheckThanhVienVaoKhuHocTap((int) maTV);
                //                System.out.println("tvInput.getMaTV(): "+tvInput.getMaTV());
                if (tvResult != null) {
                    if (!thanhVienBUS.checkViPham((int) maTV)) {
                        ttsd.setMaTV(tvResult);
                        if (thongTinSdBUS.addthongtinsd(ttsd)) {
                            JOptionPane.showMessageDialog(this, "Thêm Thành Công", "Thành công", JOptionPane.DEFAULT_OPTION);
                            loadThongTinSDTable();
                            TexMaTV.setText("");
                        } else {
                            JOptionPane.showMessageDialog(this, "Thêm Không Thành Công", "Lỗi", JOptionPane.ERROR_MESSAGE);
                            TexMaTV.setText("");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Thành Viên Vi Phạm", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        TexMaTV.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Không Phải Thành Viên", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    TexMaTV.setText("");
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnConfirmActionPerformed

    // xử lý sự kiện nút mượn thiết bị
    private void btnMuonThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuonThietBiActionPerformed
        // TODO add your handling code here:
        // trường hợp bỏ trống mã thành viên
        if (txtMaTV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã thành viên");
            return;
        }

        // trường hợp bỏ trống mã thiết bị
        if (txtMaThietBiMuon.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã thiết bị");
            return;
        }

        // trường hợp không phải là thành viên
        int maTV = Integer.parseInt(txtMaTV.getText());
        if (!thanhVienBUS.Checkthanhvien(maTV)) {
            JOptionPane.showMessageDialog(this, "Không phải là thành viên");
            return;
        }

        // trường hợp thiết bị không tồn tại
        int maTBMuon = Integer.parseInt(txtMaThietBiMuon.getText());
        if (!thietBiBUS.CheckThietBi(maTBMuon)) {
            JOptionPane.showMessageDialog(this, "Thiết bị không tồn tại");
            return;
        }
        
        if(thongTinSdBUS.getLatestThongTinSuDung(maTBMuon) != null) {
            JOptionPane.showMessageDialog(this, "Thiết bị hiện tại đang có người mượn");
            return;
        }
        
        
        LocalDateTime ldt = LocalDateTime.now();
        String strdate = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").format(ldt);
        Timestamp timestamp = Timestamp.valueOf(strdate);
        System.out.println("Mã thành viên : " + maTV);
        System.out.println("Mã thiết bị : " + maTBMuon);
        System.out.println("Thời gian mượn : " + timestamp);
        ThongTinSD ttsd = new ThongTinSD();
        ttsd.setMaTT(thongTinSdBUS.layDanhSachMuonTra().size() + 1);
        ThanhVien tvInput = new ThanhVien();
        tvInput.setMaTV(maTV);
        ThietBi tbInput = new ThietBi();
        tbInput.setMaTB(maTBMuon);
        ttsd.setMaTV(tvInput);
        ttsd.setMaTB(tbInput);
        ttsd.setTGMuon(timestamp);
        if (thongTinSdBUS.insertThongTinSuDung(ttsd)) {
            JOptionPane.showMessageDialog(this, "Mượn thiết bị thành công");
            loadDanhSachMuonTra();
            loadThongTinSDTable();
        } else {
            JOptionPane.showMessageDialog(this, "Mượn thiết bị thất bại");
        }
    }//GEN-LAST:event_btnMuonThietBiActionPerformed

    private void btnTraThietBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraThietBiActionPerformed
        // TODO add your handling code here:
        int maTBTra = Integer.parseInt(txtMaThietBiTra.getText());
        if(thongTinSdBUS.updateThoiGianTra(maTBTra)) {
            JOptionPane.showMessageDialog(this, "Trả thiết bị thành công");
            loadDanhSachMuonTra();
        } else {
            JOptionPane.showMessageDialog(this, "Trả thiết bị thất bại");
        }

    }//GEN-LAST:event_btnTraThietBiActionPerformed

    private void tableThongTinSuDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThongTinSuDungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableThongTinSuDungMouseClicked

    
    
    
    public boolean kiemTraRong(){
        boolean check = true ;
        if(txtMaThanhVien.getText().trim().isEmpty()||txtMaThanhVien.getText().trim().length()<10){
            check = false;
        }
        if(txtHoTen.getText().trim().isEmpty()){
            check = false;
        }
        if(txtKhoa.getText().trim().isEmpty()){
            check = false;
        }

        if(txtNganh.getText().trim().isEmpty()){
            check = false;
        }
        
        if(txtSoDienThoai.getText().trim().isEmpty()||txtSoDienThoai.getText().trim().length()<10){
            check = false;
        }

       
        
        
        return check;
    }
//    
//    public boolean kiemTraTrungId(String MaTV){
//         for (ThanhVien thanhVien : thanhVienBUS.layDanhSachThanhVien()) {
//             if((thanhVien.getMaTV()+"").equals(MaTV)){
//                 return false;
//             }
//        }
//         return true;
//        
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyThanhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyThanhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TexMaTV;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnMuonThietBi;
    private javax.swing.JButton btnNhapFileTv;
    private javax.swing.JButton btnSuaTv;
    private javax.swing.JButton btnThemThanhVien;
    private javax.swing.JButton btnTraThietBi;
    private javax.swing.JButton btnXoaNhieuThanhVien;
    private javax.swing.JButton btnXoaThanhVien;
    private javax.swing.JTable danhSachThanhVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMuonTra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tableThongTinSuDung;
    private javax.swing.JTable tblTTSD;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaTV;
    private javax.swing.JTextField txtMaThanhVien;
    private javax.swing.JTextField txtMaThietBiMuon;
    private javax.swing.JTextField txtMaThietBiTra;
    private javax.swing.JTextField txtNamThanhLap;
    private javax.swing.JTextField txtNganh;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
