/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import BUS.xuly2;
import com.google.protobuf.TextFormat.ParseException;
import BUS.Check;
import BUS.xulyBUS;

/**
 *
 * @author Tony
 */
public class xuliGUI extends javax.swing.JFrame {
    private xulyBUS xulyBUS = new xulyBUS();
    ArrayList<xuly2> list_xuly = xulyBUS.getXulyList();

    /**
     * Creates new form xuliGUI
     */
    public xuliGUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jDialog1 = new javax.swing.JDialog();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        maxl = new javax.swing.JTextField();
        sotien = new javax.swing.JTextField();
        hinhthucxl = new javax.swing.JComboBox<>();
        tt1 = new javax.swing.JRadioButton();
        tt0 = new javax.swing.JRadioButton();
        ngay = new com.toedter.calendar.JDateChooser();
        gio = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        matv = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                // Trả về giá trị false để không cho phép sửa thông tin trên JTable
                return false;
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        resetform = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        tieuchi = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Xử lí", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("MaXL");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("MaTV");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("HinhThucXL");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SoTien");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("NgayXL");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("TrangThaiXL");

        maxl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maxl.setPreferredSize(new java.awt.Dimension(204, 26));

        sotien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sotien.setName("sotien"); // NOI18N
        sotien.setPreferredSize(new java.awt.Dimension(204, 26));
        sotien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sotienActionPerformed(evt);
            }
        });

        hinhthucxl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hinhthucxl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khóa thẻ 1 tháng","Khóa thẻ 2 tháng","Khóa thẻ vĩnh viễn","Bồi thường","Khóa thẻ 1 tháng và bồi thường" }));
        hinhthucxl.setPreferredSize(new java.awt.Dimension(204, 26));
        hinhthucxl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinhthucxlActionPerformed(evt);
            }
        });

        tt1.setText("Đã xử lí (1)");
        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });

        tt0.setText("Chưa xử lí (0)");
        tt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt0ActionPerformed(evt);
            }
        });

        ngay.setDateFormatString("dd/M/yy");
        ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ngay.setName("ngay"); // NOI18N

        gio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        gio.setName("gio"); // NOI18N

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("DSTV");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        matv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hinhthucxl, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(matv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tt1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tt0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ngay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(maxl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton5)
                    .addComponent(matv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hinhthucxl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tt1)
                    .addComponent(tt0))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        maxl.setEditable(false);
        maxl.setText(String.valueOf(xulyBUS.createMaXL()));
        sotien.setEditable(false);
        sotien.setText("");
        ngay.setLocale(new Locale("vi", "VN"));
        matv.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(102, 102, 102))); // NOI18N

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        javax.swing.table.DefaultTableModel tableModel = new javax.swing.table.DefaultTableModel(new Object[]{ "MaXL", "MaTV", "HinhThucXL", "SoTien", "NgayXL", "TrangThaiXL" }, 0);
        for (xuly2 xl : list_xuly) {
            tableModel.addRow(new Object[]{xl.getMaXL(),xl.getMaTV(),xl.getHinhThucXL(),xl.getSoTien(),xl.getNgayXL(),xl.getTrangThaiXL()});
        }
        jTable1.setModel(tableModel);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("XỬ LÍ VI PHẠM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(541, 541, 541))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("THÊM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("XÓA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("SỬA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        resetform.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resetform.setText("Reset Form");
        resetform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetformActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resetform)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(resetform))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(60, 63, 65));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.setPreferredSize(new java.awt.Dimension(200, 27));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        tieuchi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"MaXL","MaTV" ,"Khóa thẻ 1 tháng","Khóa thẻ 2 tháng","Khóa thẻ vĩnh viễn","Bồi thường","Khóa thẻ 1 tháng và bồi thường", "0-Chưa xử lí", "1-Đã xử lí" }));
        tieuchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tieuchiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tieuchi, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tieuchi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        buttonGroup1.add(tt1);
        buttonGroup1.add(tt0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        if (maxl.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "maxl cannot be empty");
            isValid = false;
        }
        if (isValid) {
            int dialogResult = javax.swing.JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa không?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
            if (dialogResult == javax.swing.JOptionPane.YES_OPTION) {
                xulyBUS.delete(Integer.parseInt(maxl.getText()));
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                for (xuly2 xl : list_xuly) {
                    model.addRow(new Object[] { xl.getMaXL(), xl.getMaTV(), xl.getHinhThucXL(), xl.getSoTien(), xl.getNgayXL(), xl.getTrangThaiXL() });
                }
                javax.swing.JOptionPane.showMessageDialog(null, "Xóa thành công!");
            }
            
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        for (java.awt.Component component : jPanel1.getComponents()) {
            if (component instanceof javax.swing.JTextField) {
                javax.swing.JTextField textField = (javax.swing.JTextField) component;
                if (textField.getText().isEmpty() && !textField.getName().equals("sotien") && !textField.getName().equals("gio")) {
                    isValid = false;
                    break;
                }
            }
        }
        
        String hinhThucXl = tieuchi.getSelectedItem().toString();
        if (hinhThucXl.contains("bồi thường") || hinhThucXl.contains("Bồi thường")) {
            if (sotien.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Số tiền không được để trống khi hình thức xử lý có 'bồi thường'");
                isValid = false;
            }
        }
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(this, "All text fields must be filled", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        // Check if 'ngay' is not empty
        if (ngay.getDate() == null) {
            java.util.Date currentDate = new java.util.Date();
            ngay.setDate(currentDate);
        }
        // Check if 'gio' is not empty and in correct format
        String gioPattern = "([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]";
        if (gio.getText().isEmpty() || !gio.getText().matches(gioPattern)) {
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
            Date date = new Date();
            gio.setText(formatter.format(date));
        }
        // Check if 'trangthaixl' is not empty
        if (!tt0.isSelected() && !tt1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Trạng thái không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        if(isValid == true){
            int dialogResult = javax.swing.JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm không?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
            if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
                xuly2 xuly = new xuly2();
                xuly.setMaXL(Integer.parseInt(maxl.getText()));
                xuly.setMaTV(Integer.parseInt(matv.getText()));
                xuly.setHinhThucXL(hinhthucxl.getSelectedItem().toString());
                if (sotien.getText().isEmpty()) {
                    xuly.setSoTien(null);
                } else {
                    xuly.setSoTien(Integer.parseInt(sotien.getText()));
                }
                xuly.setNgayXL(Check.Date_String(ngay.getDate())+" "+gio.getText());
                xuly.setTrangThaiXL(tt1.isSelected() ? 1 : 0);
                xulyBUS.add(xuly);
                ((DefaultTableModel) jTable1.getModel()).addRow(new Object[] { xuly.getMaXL(), xuly.getMaTV(), xuly.getHinhThucXL(), xuly.getSoTien(), xuly.getNgayXL(), xuly.getTrangThaiXL() });
                maxl.setText(String.valueOf(xulyBUS.createMaXL()));
                javax.swing.JOptionPane.showMessageDialog(null, "Thêm thành công!");
            }
        }
        // You can now use the variables 'ngay' and 'trangThai' in your code
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jTextField1ActionPerformed

    private void tt0ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tt0ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tt0ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        boolean isValid = true;
        for (java.awt.Component component : jPanel1.getComponents()) {
            if (component instanceof javax.swing.JTextField) {
                javax.swing.JTextField textField = (javax.swing.JTextField) component;
                if (textField.getText().isEmpty() && !textField.getName().equals("sotien")) {
                    isValid = false;
                    break;
                }
            }
        }
        String hinhThucXl = tieuchi.getSelectedItem().toString();
        if (hinhThucXl.contains("bồi thường") || hinhThucXl.contains("Bồi thường")) {
            if (sotien.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Số tiền không được để trống khi hình thức xử lý có 'bồi thường'");
                isValid = false;
            }
        }
        if (!isValid) {
            javax.swing.JOptionPane.showMessageDialog(this, "All text fields must be filled", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
       // Check if 'ngay' is not empty
        if (ngay.getDate() == null) {
            java.util.Date currentDate = new java.util.Date();
            ngay.setDate(currentDate);
        }
        // Check if 'gio' is not empty and in correct format
        String gioPattern = "([01]?[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]";
        if (gio.getText().isEmpty() || !gio.getText().matches(gioPattern)) {
            SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
            Date date = new Date();
            gio.setText(formatter.format(date));
        }
        // Check if 'trangthaixl' is not empty
        if (!tt0.isSelected() && !tt1.isSelected()) {
            JOptionPane.showMessageDialog(this, "Trạng thái không được để trống", "Thông báo", JOptionPane.ERROR_MESSAGE);
            isValid = false;
        }
        if(isValid == true){
            int dialogResult = javax.swing.JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa không?", "Xác nhận", javax.swing.JOptionPane.YES_NO_OPTION);
            if(dialogResult == javax.swing.JOptionPane.YES_OPTION){
                xuly2 xuly = new xuly2();
                xuly.setMaXL(Integer.parseInt(maxl.getText()));
                xuly.setMaTV(Integer.parseInt(matv.getText()));
                xuly.setHinhThucXL(hinhthucxl.getSelectedItem().toString());
                if (sotien.getText().isEmpty()) {
                    xuly.setSoTien(null);
                } else {
                    xuly.setSoTien(Integer.parseInt(sotien.getText()));
                }
                xuly.setNgayXL(Check.Date_String(ngay.getDate())+" "+gio.getText());
                xuly.setTrangThaiXL(tt1.isSelected() ? 1 : 0);
                xulyBUS.update(xuly);
                int selectedRow = jTable1.getSelectedRow();
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getMaXL(), selectedRow, 0);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getMaTV(), selectedRow, 1);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getHinhThucXL(), selectedRow, 2);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getSoTien(), selectedRow, 3);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getNgayXL(), selectedRow, 4);
                ((DefaultTableModel) jTable1.getModel()).setValueAt(xuly.getTrangThaiXL(), selectedRow, 5);
                javax.swing.JOptionPane.showMessageDialog(null, "Sửa thành công!");
            }
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tt1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tt1ActionPerformed

    private void resetformActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        // Iterate over all components in the panel
        for (java.awt.Component component : jPanel1.getComponents()) {
            // Check if the component is a JTextField
            if (component instanceof javax.swing.JTextField) {
                // Cast the component to JTextField and reset its text
                ((javax.swing.JTextField) component).setText("");
            }
        }
        maxl.setText(String.valueOf(xulyBUS.createMaXL()));
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable target = (JTable) evt.getSource();
            int row = target.getSelectedRow();
            // Lấy dữ liệu từ JTable
            maxl.setText(jTable1.getValueAt(row, 0).toString());
            matv.setText(jTable1.getValueAt(row, 1).toString());
            hinhthucxl.setSelectedItem(jTable1.getValueAt(row, 2).toString());
            if (jTable1.getValueAt(row, 3) == null) {
                sotien.setText("");
            } else {
                sotien.setText(jTable1.getValueAt(row, 3).toString());
            }
            String[] parts = jTable1.getValueAt(row, 4).toString().split(" ");
            try {
                ngay.setDate(Check.String_Date(parts[0]));
            } catch (ParseException | java.text.ParseException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
            gio.setText(parts[1]);
            if (jTable1.getValueAt(row, 5).toString().equals("1")) {
                tt1.setSelected(true);
            } else {
                tt0.setSelected(true);
            }
        }
    }// GEN-LAST:event_jTable1MouseClicked
    private static String maTV_DSTV;
    public static String getMaTV(){
        return maTV_DSTV;
    }
    public static void setMaTV(String maTV){
        maTV_DSTV = maTV;
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new DSTV();

        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
        frame.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        frame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                int option = JOptionPane.showConfirmDialog(null, "Chọn MaTV này!!", "Xác nhận", JOptionPane.YES_NO_OPTION);
                    if (option == JOptionPane.YES_OPTION) {
                        matv.setText(getMaTV());
                    }else{
                    }
            }
        });
    }// GEN-LAST:event_jButton5ActionPerformed

    private void sotienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sotienActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sotienActionPerformed

    private void hinhthucxlActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_hinhthucxlActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String) hinhthucxl.getSelectedItem();
        if (selectedOption.contains("bồi thường") || selectedOption.contains("Bồi thường")) {
            sotien.setEditable(true);
        } else {
            sotien.setEditable(false);
        }
    }// GEN-LAST:event_hinhthucxlActionPerformed

    private int getIndexOfColumn(String columnName) {
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            if (jTable1.getColumnName(i).equals(columnName)) {
                return i;
            }
        }
        return -1;
    }

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String searchValue = jTextField1.getText();
        String selectedCriterion = (String) tieuchi.getSelectedItem();

        // Assuming jTable1 is your JTable and tableModel is its model
        javax.swing.table.TableModel tableModel = jTable1.getModel();

        if (searchValue.isEmpty()) {
            // If the search field is empty, show all rows
            ((javax.swing.table.DefaultTableModel) tableModel).setRowCount(0);
            // Assuming you have a method to populate all rows
            populateAllRows();
        } else {

            // If the search field is not empty, filter rows
            for (int rowIndex = 0; rowIndex < tableModel.getRowCount(); rowIndex++) {
                Object cellValue = tableModel.getValueAt(rowIndex, getIndexOfColumn(selectedCriterion));
                if (cellValue != null && !cellValue.toString().contains(searchValue)) {
                    // Remove the row if it does not match the search value
                    ((javax.swing.table.DefaultTableModel) tableModel).removeRow(rowIndex);
                    rowIndex--; // Adjust the index due to the removal of row
                }

            }

        }

    }

    // TODO: Add code to populate all rows in the table
    private void populateAllRows() {
        // javax.swing.table.DefaultTableModel tableModel = new
        // javax.swing.table.DefaultTableModel(new Object[]{ "MaXL", "MaTV",
        // "HinhThucXL", "SoTien", "NgayXL", "TrangThaiXL" }, 0);
        javax.swing.table.DefaultTableModel tableModel = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        for (xuly2 xl : list_xuly) {
            tableModel.addRow(new Object[] { xl.getMaXL(), xl.getMaTV(), xl.getHinhThucXL(), xl.getSoTien(),
                    xl.getNgayXL(), xl.getTrangThaiXL() });
        }

    }// GEN-LAST:event_jTextField1KeyReleased

    private void tieuchiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tieuchiActionPerformed
        // TODO add your handling code here:
        String selectedCriterion = (String) tieuchi.getSelectedItem();
        if (selectedCriterion.equals("MaXL") || selectedCriterion.equals("MaTV")){
            jTextField1.setEditable(true);
        }
        if (selectedCriterion.equals("Khóa thẻ 1 tháng") || selectedCriterion.equals("Khóa thẻ 2 tháng")
                || selectedCriterion.equals("Khóa thẻ vĩnh viễn") || selectedCriterion.equals("Bồi thường")
                || selectedCriterion.equals("Khóa thẻ 1 tháng và bồi thường")) {
            jTextField1.setEditable(false);
            javax.swing.table.DefaultTableModel tableModel2 = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            tableModel2.setRowCount(0);
            for (xuly2 xl : list_xuly) {
                if (xl.getHinhThucXL().equals(selectedCriterion)) {
                    tableModel2.addRow(new Object[] { xl.getMaXL(), xl.getMaTV(), xl.getHinhThucXL(), xl.getSoTien(),
                            xl.getNgayXL(), xl.getTrangThaiXL() });
                }
            }
        }
        if(selectedCriterion.equals("0-Chưa xử lí") || selectedCriterion.equals("1-Đã xử lí")){
            jTextField1.setEditable(false);
            javax.swing.table.DefaultTableModel tableModel2 = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            tableModel2.setRowCount(0);
            for (xuly2 xl : list_xuly) {
                if (String.valueOf(xl.getTrangThaiXL()).equals(selectedCriterion.substring(0,1))) {
                    tableModel2.addRow(new Object[] { xl.getMaXL(), xl.getMaTV(), xl.getHinhThucXL(), xl.getSoTien(),
                            xl.getNgayXL(), xl.getTrangThaiXL() });
                }
            }
        }

    }// GEN-LAST:event_tieuchiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(xuliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(xuliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(xuliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(xuliGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new xuliGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField gio;
    private javax.swing.JComboBox<String> hinhthucxl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JTextField matv;
    private javax.swing.JTextField maxl;
    private com.toedter.calendar.JDateChooser ngay;
    private javax.swing.JButton resetform;
    private javax.swing.JTextField sotien;
    private javax.swing.JComboBox<String> tieuchi;
    private javax.swing.JRadioButton tt0;
    private javax.swing.JRadioButton tt1;
    // End of variables declaration//GEN-END:variables
}
